

KRD={
    1:'BAACAgIAAxkBAAEOfvxiJLqDCnKOI25Av2GcweBAoliyrgACXRYAAtZKKUkAATpjYv3HwMkjBA'
}
Pharh={
    1:"BAACAgIAAxkBAAEOleJiKNJXVE_NEes-yBZp8wjxFfsg9QACjhMAAsrQ0EqrabbcxRjlyyME",
    2:"BAACAgIAAxkBAAEOleRiKNJ2GTtnSSZFwU6LS7cR4tYrcQACvxkAAv3UGEuWOv1T04zgbiME",
    3:"BAACAgIAAxkBAAEOleZiKNKESvmQ7jmp75cMJPC6nRqS2wACdxAAAkN5aEu33rVj2hRuOiME"
}
Zugumomo={
    1:"BAACAgIAAxkBAAEOlehiKNLStQfJzzUcOXqqJp9S_EkFYgACNgIAAlruWUiv_u-eQV5zPiME",
    2:"BAACAgIAAxkBAAEOleliKNLS5zVqM5GOiNyC4l1ZUk6uZwACMwIAAvZEUEhz97gWI76P2yME",
    3:"BAACAgIAAxkBAAEOlepiKNLSSbOpqLLfGTUBlxMKvLfgYQACNwIAAlruWUiJ3Sp3PN8NiyME",
    4:"BAACAgIAAxkBAAEOletiKNLSf8pj0UxOqW_HEYDVdITk-gACNAIAAvZEUEj0JnA3hBB-ZSME",
    5:"BAACAgIAAxkBAAEOlexiKNLSXg-sV9E6Hvuvaaq0R203vwACOAIAAlruWUjIpiTxHqBVCiME",
    6:"BAACAgIAAxkBAAEOle1iKNLSTyyWrz62_SI16VC8WH7cAAM5AgACWu5ZSL4YQaSauU2MIwQ",
    7:"BAACAgIAAxkBAAEOle5iKNLSpjc7xmShDj6y6ZF3h45MVAACOgIAAlruWUjGOrgCH-Ex2yME",
    8:"BAACAgIAAxkBAAEOle9iKNLSIEY2Eb23zOA1SKlt2GucKQACOwIAAlruWUi5JYCbVP4akCME",
    9:"BAACAgIAAxkBAAEOlfBiKNLSCXRBEoP4rTvoip26wULdzwACPAIAAlruWUgRsByJ8Uw4xCME",
    10: "BAACAgIAAxkBAAEOlfFiKNLSi0GW7l1NnJIneNzUYTbmuQACPQIAAlruWUgnCk-mSP7mGCME",
    11:"BAACAgIAAxkBAAEOlghiKNOUHYgl1NgPTOyilpntl_k6_QACPwIAAlruWUhoUgABpHUPiv8jBA",
    12:"BAACAgIAAxkBAAEOlgliKNOUm8Ow-x-SV5HC-RjYPTPz6wACOgIAAvZEUEhcEg_haJpA6iME",

}

MHA={

    1:"BAACAgIAAxkBAAEOuIpiLvqBtmwhvy2MIro_8pkXPse6fAACNAgAAqzEYUklsYoS8voyeSME",
    2:"BAACAgIAAxkBAAEOuIxiLvqYZ2A8VnbkKwMvRtWy8s8RaQACNwgAAqzEYUliUujnoe46XiME",
    3:"BAACAgIAAxkBAAEOuI5iLvqq3-MpJ-6E3Do5JO-2rElkVAACPAgAAqzEYUm2NaJ1GH6sYiME",
    4:"BAACAgIAAxkBAAEOuJBiLvqzhLccycO-mxkUirJRNXHX3QACPwgAAqzEYUk3JILuUwKPfiME",
    5:"BAACAgIAAxkBAAEOuJRiLvq5W0UV9MMFWwx0rvdLypydqAACQAgAAqzEYUlS3xEl_pZ4fCME",
    6:"BAACAgIAAxkBAAEOuJZiLvq-Uo51_a1tlPbLoZUgfsFQiwACRggAAqzEYUnnJoy7VNHemCME",
    7:"BAACAgIAAxkBAAEOuJpiLvsUlBLWfWE7Crmkai40y1eR-wACXQgAAqzEYUlII-LbIZ-g1CME",
    8:"BAACAgIAAxkBAAEOuJxiLvsbPMzBbc5uCZCqa05i9aUPIQACXwgAAqzEYUn5RP9APksVlyME",
    9:"BAACAgIAAxkBAAEOuJ5iLvsj8MWdvD-72AeKdGGjsFn0FQACawgAAqzEYUmx89rwdTq51SME",
    10: "BAACAgIAAxkBAAEOuKJiLvsp2Zhqe8UCuKAxm4VVuid76wACbQgAAqzEYUkbuh4_yY7F_iME",
    11:"BAACAgIAAxkBAAEOuKZiLvsxa2GxbVFU2wkSeS5Q-Pg5XQACbwgAAqzEYUm95Drd2rhwciME",
    12:"BAACAgIAAxkBAAEOuKpiLvs3EC-BjOyXGX5_k9DEVcinvQACcAgAAqzEYUkdv7zvDjFS6SME",
    13:"BAACAgIAAxkBAAEOuK5iLvs-LwcsRKhfOG5Inj3U7sctbgACcwgAAqzEYUm9ra8KA6SNiSME",
}
ehoTerrora={}
sharlotta={}
devochkaZayka={}
KRD2={}
codeGeass={}
codeGeass2={}
tvoeImya={
     1:"BAACAgIAAxkBAAEOz4ViNHOQNkBQ-B4xRbqn8-EyPbQwbAACrA8AAmir0Uq_ZnW0jxU-YyME"
}

dityaShud={1:'BAACAgIAAxkBAAEOz49iNHTWvsEYAAEHwG0gu4smjycXLVYAAiIGAAIHncFJf0EIH5epAAF7IwQ'}
KRDInfinityPoezd={1:'BAACAgIAAxkBAAEOz41iNHTOHtxIjQl-dDfVLDgEz9VntQACnhEAAqk5QUjAx-sFe3OB1SME'}

Maindict={
    1:KRD,
    2:Pharh,
    3:Zugumomo,
    4: MHA,
    5:ehoTerrora,
    6:sharlotta,
    7:devochkaZayka,
    8:KRD2,
    9:codeGeass,
    10:codeGeass2,
    100:tvoeImya,
    101:dityaShud,
    102:KRDInfinityPoezd,
}





FilmDict={
    1:tvoeImya,
    2:dityaShud,
    3:KRDInfinityPoezd,

}
